#!/bin/bash
# --------------------------------------------------------------------------------------------------
# Process to keep the rrdlogger alive and well.
#
# v1.0                                                                         C.Paus (Apr 13, 2014)
# --------------------------------------------------------------------------------------------------
if [ -e "/usr/local/PausHaus/RrdLogger/setup.sh" ]
then
  source /usr/local/PausHaus/RrdLogger/setup.sh
else
  echo " Could not find the standard setup.sh (in /usr/local/PausHaus/RrdLogger). EXIT!"
  exit 1
fi

while [ 1 ]
do
  # make sure the log directory exists
  mkdir -p $RRDLOGGER_LOGDIR
  if [ -e "$RRDLOGGER_LOGDIR" ]
  then
    #echo " RrdLogger log area exists. Let's start!"
    sleep 1
  else
    echo ""
    echo " RrdLogger log area could not be found ($RRDLOGGER_LOGDIR). EXIT!"
    echo ""
    exit 1
  fi

  # generate specific log file
  tag=`date "+%s"`
  logFile=$RRDLOGGER_LOGDIR/rrdlogger-$tag.log
  touch $logFile

  # ten loops over the process with one logfile (keep it small)
  for index in `echo 0 1 2 3 4 5 6 7 8 9`
  do
    # enter tag into the logfile
    echo " rrdlogger loop $index  -- $tag"  >> $logFile
    # call the logger
    $RRDLOGGER_DIR/rrdLogger.pl             >> $logFile

    # sleep for 10 minutes
    sleep 600
  done

done

exit 0;
